### ISSUE TITLE
UDP messages not getting picked up

### ISSUE THREAD

**Issue by koraysels** [dusanmsk/railduino-udp#6]
I really can't get this to work with my loxone.. I flashed the correct firmware and checked my loxone settings (see screenshots)

I don't undertand why it is not working? I tried all possible combinations .. please has anybody got this worling with UDP ?

![image](https://user-images.githubusercontent.com/2418853/34654986-a4eae1f8-f403-11e7-8c4b-0bd3ef53ad0b.png)

![image](https://user-images.githubusercontent.com/2418853/34654993-bc06692a-f403-11e7-8a56-eb9c6afb7f0d.png)

**Comment by PavSedl** [comment]
Please check your Command for ON and OFF - there should be string for relay output - "do" instead of "ro" ... e.g. "rail4 do6 on"

**Comment by koraysels** [comment]
Hi, i tried  do6 and ro6 and rail1 to rail4 ... still nothing.. Also how can I check if the device is in my network ? It does not respond to ping ...

**Comment by PavSedl** [comment]
OK, then first you need to check your LAN connection to your Railduino. You should see the device in your router's administration once it is given with IP address.

**Comment by koraysels** [comment]
Well i can’t see it. My entire Home network is 
Based on the subnet structure 192.168.1.xx
And I cannot find 192.168.150.151 on my network..

**Comment by dusanmsk** [comment]
It doesn't matter what ip addres has loxone and what addres has railduino. Railduino sets it's address indepedently and statically using address dip switch.

The only requirement is to have loxone and railduino in single physical network (switch), because it uses udp broadcasts which doesn't pass through routers.

Connect loxone and railduino directly to single switch, re-check your loxone configuration and it shoukd work.

**Comment by koraysels** [comment]
They are connected to a single 10port gigabit switch (the lights on the ethernet shield are blinking and the miniserver also has a solid connection)

So I don't need to input an address in the Address field of the loxone virtual output ? Can't I check it with a tool or something? I tried packetsender to send UDP packets manually (whithout always having to reflash the miniserver) but nothing works..

**Comment by dusanmsk** [comment]
You should check what's going on with wireshark and filter by "udp && udp.port == 44444" for relays or "udp && udp.port == 55555" for inputs

**Comment by koraysels** [comment]
alright I'll do that when I'm back home tongiht! I hope my railduino is not broken or something :) 

Thanks for your time man

**Comment by PavSedl** [comment]
Are you sure that you reflashed Railduino correctly ? You have bought Modbus TCP version of Railduino ...

**Comment by koraysels** [comment]
@PavSedl I bought the TCP modbus version with the ethernet shield and the mega 2560 R3, that is correct. I flashed the hex file using different methods, I even tried once with compiling it myself in the arduino IDE and flashing it directly to no avail.. It might be something stupid that I am missing.. But I can't seem to fix it.. I will check with wireshark and sniff the UDP messages in my local network tonight when I'm back home.

**Comment by alxzndr** [comment]
@koraysels I had a similar problem.
After 2 days of debugging I found out it was caused by a bad ethernet shield.
I replaced it with another ethernet shield i had lying around and everything started working perfectly.

**Comment by koraysels** [comment]
![image](https://user-images.githubusercontent.com/2418853/34683210-a6de89bc-f4a1-11e7-9b5b-2655fdab2dfa.png)

well it does look like the ud packages are being sent from my miniserver to the broadcast address, but I cant hear relays clicking or see my lights turn on :( damn

**Comment by PavSedl** [comment]
OK, please try to see in Loxone Config UDP monitor if it gets any packets from Railduino when set some of the digital inputs on.

**Comment by koraysels** [comment]
hmm I replaced the ethernet shield with a genuine ARDUINO ethernet shield onstead of the one that came with the railduino..now it works..

**Comment by PavSedl** [comment]
Ouch, so bad shield ? if you are willing to send me the one which is not working, I will send you another one. You have ordered the Railduino more then a year ago - and in that time there were some technical issues with the ethernet shields

**Comment by koraysels** [comment]
sure thing!  send me an email with the specifics. you have my emailaddress right ?
